# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: James Fleming
email: j.fleming@lboro.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  James Fleming's webpages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "jflmng.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  jflmng
minimal_mistakes_skin: default
search: true

# Navigation
navigation:
  main:
    - title: "About"
      url: /about/
    - title: "Research"
      url: /research/
    - title: "Publications"
      url: /publications/
    - title: "Presentations"
      url: /presentations/

# Author / Sidebar
author:
  name: "James Fleming"
  avatar: "/assets/images/profile.jpg" # You might need to add this image later
  bio: "Senior Lecturer in Intelligent Control Systems"
  location: "Loughborough, UK"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:j.fleming@lboro.ac.uk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jflmng"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar-square mobile-only" # academicons
      url: "https://scholar.google.com/citations?user=qXhzsAMAAAAJ"

# Google analytics tag
google_analytics: G-ZYS6HM1QMD

# Pagination
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Build settings
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed

# Minima skin to use (Disabled)
# minima:
#   skin: classic

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
